[phases.setup]
nixPkgs = ["python311"]

[phases.build]
cmds = [
  "python3 -m venv /app/.venv",
  "/app/.venv/bin/pip install -r backend/datashop/requirements.txt",
  "/app/.venv/bin/python backend/datashop/manage.py collectstatic --noinput",
  "/app/.venv/bin/python backend/datashop/manage.py migrate"
]

[start]
cmd = "cd backend/datashop && /app/.venv/bin/gunicorn core.wsgi:application --bind 0.0.0.0:$PORT --workers 2"
