# Generated by Django 6.0.3 on 2026-04-04 11:02

import transactions.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('data', 'Data Bundle'), ('airtime', 'Airtime'), ('electricity', 'Electricity'), ('tv', 'TV Subscription'), ('exam', 'Exam Pin')], max_length=20)),
                ('payload', models.JSONField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('scheduled_at', models.DateTimeField()),
                ('recurrence', models.CharField(choices=[('once', 'One Time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='once', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('executed', 'Executed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='active', max_length=20)),
                ('last_executed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'scheduled_transactions',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('data', 'Data Bundle'), ('airtime', 'Airtime'), ('electricity', 'Electricity'), ('tv', 'TV Subscription'), ('exam', 'Exam Pin')], max_length=20)),
                ('service_provider', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('reference', models.CharField(default=transactions.models.generate_reference, max_length=50, unique=True)),
                ('external_reference', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
