# Generated by Django 6.0.3 on 2026-04-04 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityDisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('vtpass_service_id', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'electricity_discos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExamProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(choices=[('waec', 'WAEC'), ('jamb', 'JAMB'), ('neco', 'NECO'), ('nabteb', 'NABTEB')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('vtpass_variation_code', models.CharField(max_length=100)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'exam_products',
                'ordering': ['body', 'sell_price'],
            },
        ),
        migrations.CreateModel(
            name='ServiceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('data', 'Data Bundles'), ('airtime', 'Airtime'), ('electricity', 'Electricity'), ('tv', 'TV Subscription'), ('exam', 'Exam Pins')], max_length=20, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('maintenance_message', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'service_configs',
            },
        ),
        migrations.CreateModel(
            name='TVProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('vtpass_service_id', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tv_providers/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tv_providers',
            },
        ),
        migrations.CreateModel(
            name='DataPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('mtn', 'MTN'), ('airtel', 'Airtel'), ('glo', 'Glo'), ('9mobile', '9mobile')], max_length=20)),
                ('vendor_type', models.CharField(choices=[('sme', 'SME'), ('gifting', 'Gifting'), ('corporate_gifting', 'Corporate Gifting'), ('corporate', 'Corporate'), ('reseller', 'Reseller')], default='sme', max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('vtpass_id', models.CharField(blank=True, max_length=100)),
                ('size_mb', models.PositiveIntegerField()),
                ('size_display', models.CharField(max_length=20)),
                ('validity_days', models.PositiveIntegerField()),
                ('validity_display', models.CharField(max_length=30)),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'data_plans',
                'ordering': ['network', 'vendor_type', 'size_mb'],
                'unique_together': {('network', 'vendor_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TVPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vtpass_variation_code', models.CharField(max_length=100)),
                ('duration_months', models.PositiveIntegerField(default=1)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='services.tvprovider')),
            ],
            options={
                'db_table': 'tv_plans',
                'ordering': ['provider', 'sell_price'],
            },
        ),
    ]
